name: Continuous Delivery

on:
  push:
    branches: ["main"]

env:
  IMAGE_NAME: ecopower
  DOCKER_USERNAME: marcosnasccode

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      - name: Rename .jar to a fixed name
        run: |
          mkdir -p target
          cp target/*.jar target/app.jar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:v1

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    if: github.repository == 'marcosnasccode/staging'
    steps:
      - name: Deploy to Azure Staging
        uses: azure/webapps-deploy@v2
        with:
          app-name: ecopower-staging
          publish-profile: ${{ secrets.AZURE_PROFILE_STAGING }}
          images: '${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:v1'

  deploy-production:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.repository == 'marcosnasccode/main'
    steps:
      - name: Deploy to Azure Production
        uses: azure/webapps-deploy@v2
        with:
          app-name: EcoPowerProj
          publish-profile: ${{ secrets.AZURE_PROFILE }}
          images: '${{ env.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:v1'
